version: '3'
services:
  threadsthunksup:
    image: "registry.cn-hangzhou.aliyuncs.com/vivavideo/vcmvideoinfo:0.0.1"
    container_name: "threadsthunksup"
    depends_on:
      - mysql-db
    volumes:
      - ./public/assets:/f2e/download/vcmvideoinfo/public/assets
    ports:
      - "5072:80"
    environment:
      - NODE_ENV=production 

  mysql-db:
    image: mysql:5.6
    container_name: "threadsthunksup_db"
    hostname: "threadsthunksup_db"
    restart: always
    environment :
      MYSQL_USER: root      
      #MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"      
      MYSQL_DATABASE: tt_upload
      MYSQL_ROOT_HOST: "%"
    ports:
      - '3308:3308'
    volumes:
      - ./doc:/f2e/download/vcmvideoinfo/doc/
      - ./mysql/config/my.cnf:/etc/my.cnf       
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/

# volumes:
#   ttup-files-volume:
#   ttup-db-volume:    


# docker inspect threadsthunksup